### ISSUE TITLE
Error database type mysql not supported

### ISSUE THREAD

**Issue by Fmarra** [ndunand/moodle-tool_mergeusers#100]
Hello all,
I've just installed the plugin in my Moodle and I receive this error message when I try to merge users accounts (site admin/users/merge users/merge users).

rror: Database type mysql not supported.

More information about this error

Debug info: 
Error code: errordatabase
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 377 of /admin/tool/mergeusers/lib/mergeusertool.php: call to print_error()
line 195 of /admin/tool/mergeusers/lib/mergeusertool.php: call to MergeUserTool->checkDatabaseSupport()
line 71 of /admin/tool/mergeusers/index.php: call to MergeUserTool->__construct()

**Comment by ndunand** [comment]
Hi, can you please specify which exact version of Moodle and of the tool_mergeusers plugin you're using?

**Comment by federicama** [comment]
Hi, it always me but my previous account wasn't working!
We are using Moodle 2.8.5 and the plugin version is 1.10.2 (Build: 2015022001) (2015022001)

**Comment by federicama** [comment]
I also tried with the previous version of the plugin:1.10.1 (Build: 2015022000) (2015022000) and the error message is the same.

**Comment by ndunand** [comment]
Hello, could you check what is the value of `$CFG->dbtype` in your Moodle's `config.php` file?

**Comment by federicama** [comment]
Ehi, sorry but I don't know where to look at. I don't have access to the server, is there a place in Moodle where I can go?

**Comment by jpahullo** [comment]
Yes, you can visit as administrator the following URL: http://YOURMOODLE.COM/admin/environment.php

and send us the line starting by "database".

Thanks!

**Comment by Fmarra** [comment]
Ehi (now it looks like I have two accounts!), here's the line:

database	mysql (5.5.41-0ubuntu0.14.04.1)	version 5.5.31 is required and you are running 5.5.41.0.0.14.04.1		OK

**Comment by ndunand** [comment]
@jpahullo I think our plugin is not happy because `dbtype` is equal to `mysql` instead of `mysqli`. This older driver is not supported officially by Moodle anymore (at least, it is not listed as an option in `config-dist.php`).

**Comment by jpahullo** [comment]
I see. I think other times we suggested to change its definition from "mysql" to "mysqli" in the config.php, since they are equivalent. Other times always worked ok.

Is there a way of secure testing @Fmarra ?

**Comment by ndunand** [comment]
Yes, I also think changing this parameter would be only beneficial: better performance (if any) and better support.

**Comment by jpahullo** [comment]
You take my 10 points @ndunand :smiley_cat:  You're right!

**Comment by Fmarra** [comment]
Hello, sorry if I didn't answer you in first instance but I was off from work. I'm going to contact our server admin and come back to you as soon as I have news. Thanks!

**Comment by Fmarra** [comment]
Hi everyone! My server administrator changed the line in the config.php and I tried to install again the plugin. The result is this one:

Debug info: Table 'mdl_tool_mergeusers' already exists
CREATE TABLE mdl_tool_mergeusers (
id BIGINT(10) NOT NULL auto_increment,
touserid BIGINT(10) NOT NULL,
fromuserid BIGINT(10) NOT NULL,
success SMALLINT(4) NOT NULL,
timemodified BIGINT(10) NOT NULL,
log LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
CONSTRAINT PRIMARY KEY (id)
, KEY mdl_toolmerg_tou2_ix (touserid)
, KEY mdl_toolmerg_fro2_ix (fromuserid)
, KEY mdl_toolmerg_suc2_ix (success)
, KEY mdl_toolmerg_toufrosuc2_ix (touserid, fromuserid, success)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE = utf8_general_ci
COMMENT='List of merged users: data from fromuserid user is merged in'
Error code: ddlexecuteerror
Stack trace:

    line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
    line 905 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
    line 412 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
    line 364 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
    line 500 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
    line 1626 of /lib/upgradelib.php: call to upgrade_plugins()
    line 434 of /admin/index.php: call to upgrade_noncore()

And now I cannot do anything except to stay in the Plugins check page. Help, please!

**Comment by ndunand** [comment]
Hello,

It seems that Moodle is somehow trying to install the plugin, but it is already installed (can't think of why, as it obviously was already installed before).

I think you could simply rename the `/admin/tool/mergeusers/db/install.xml` file from your Moodle, for instance just rename it to `install.off`.

**Comment by Fmarra** [comment]
It looks strange to me because I'm pretty sure I uninstalled it, but maybe I had to purge the caches? (?!?)

Thanks for the answer, I will let you know.

**Comment by federicama** [comment]
Hello everyone, sorry for the late reply.
I just wanted to tell you that everything worked out in the end. I didn't really understand what was the issue, but the server administrator fixed it. 
I think the issue can be closed. :)

Thanks for your help and support!

**Comment by jpahullo** [comment]
It's great and thanks for coming back and reporting it.

@ndunand, as suggested, I think this issue can be closed, too.
