### ISSUE TITLE
Make it work on Moodle 2.9

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#102]
Test it works correctly on Moodle 2.9.

We have already a warning from the Moodle forum, from Gary, stating it does not work.

> Thanks Jordi
> i have tried to use with 2.9 but it throws up an error as follows
>
>For further reference, these results are recorded in the log id 2.
> Some error occurred:
>
> Exception thrown when merging: 'Error writing to database".
>
> Trace:
>#0 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(244): moodle_database->query_end(false)
>#1 /var/www/moodle/lib/dml/pgsql_native_moodle_database.php(682): >pgsql_native_moodle_database->query_end(false)
>#2 /var/www/moodle/admin/tool/mergeusers/lib/table/generictablemerger.php(225): >pgsql_native_moodle_database->execute('UPDATE mdl_cour...')
>#3 /var/www/moodle/admin/tool/mergeusers/lib/table/generictablemerger.php(80): >GenericTableMerger->updateRecords(Array, Array, 'userid', Array, Array)
>#4 /var/www/moodle/admin/tool/mergeusers/lib/mergeusertool.php(281): GenericTableMerger->merge(Array, Array, Array)
>#5 /var/www/moodle/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('15104', '2202')
>#6 /var/www/moodle/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('15104', '2202')
>#7 {main}
>
>
>Merge failed!
>Your database engine supports transactions. Therefore, the whole current transaction has been rolled back and no modification has been made to your database.
>
>Hope this helps sonrisa
>Regards
>Gary
>
>

**Comment by ndunand** [comment]
Another error (on MySQL):

    Exception thrown when merging: 'Error writing to database".
    Duplicate entry '22784-2941-1343' for key 'mdl_courcompcritcomp_useco_uix'
    Trace:
    #0 /.../lib/dml/mysqli_native_moodle_database.php(974): moodle_database->query_end(false)
    #1 /.../admin/tool/mergeusers/lib/table/generictablemerger.php(225): mysqli_native_moodle_database->execute('UPDATE mdl_cour...')
    #2 /.../admin/tool/mergeusers/lib/table/generictablemerger.php(80): GenericTableMerger->updateRecords(Array, Array, 'userid', Array, Array)
    #3 /.../admin/tool/mergeusers/lib/mergeusertool.php(281): GenericTableMerger->merge(Array, Array, Array)
    #4 /.../admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('22784', '29238')
    #5 /.../admin/tool/mergeusers/index.php(135): MergeUserTool->merge('22784', '29238')
    #6 {main}

**Comment by jpahullo** [comment]
I found this about the given compound index:

```
CREATE TABLE mdl_course_completion_crit_compl (
id BIGINT(10) NOT NULL auto_increment,
userid BIGINT(10) NOT NULL DEFAULT 0,
course BIGINT(10) NOT NULL DEFAULT 0,
criteriaid BIGINT(10) NOT NULL DEFAULT 0,
gradefinal NUMERIC(10,5),
unenroled BIGINT(10),
timecompleted BIGINT(10),
CONSTRAINT PRIMARY KEY (id)
, KEY mdl_courcompcritcomp_use_ix (userid)
, KEY mdl_courcompcritcomp_cou_ix (course)
, KEY mdl_courcompcritcomp_cri_ix (criteriaid)
, KEY mdl_courcompcritcomp_tim_ix (timecompleted)
, UNIQUE KEY mdl_courcompcritcomp_useco_uix (userid, course, criteriaid)
)
```

We should have to add this at the compoundindexes section in config/config.php:

```
         'course_completion_crit_compl' => array( // unique key mdl_courcompcritcomp_useco_uix
            'userfield' => array('userid'),
            'otherfields' => array('course', 'criteriaid'),
        ),
```

Hoping this helps!

Jordi

**Comment by ndunand** [comment]
Thanks @jpahullo , indeed it works fine now :+1:

**Comment by ndunand** [comment]
Another thing:

    events_trigger() is deprecated, please use new events instead
        line 387 of /lib/deprecatedlib.php: call to debugging()
        line 223 of /admin/tool/mergeusers/lib/mergeusertool.php: call to events_trigger()
        line 135 of /admin/tool/mergeusers/index.php: call to MergeUserTool->merge()

**Comment by jpahullo** [comment]
Thanks for the feedback, but thi deprecated stuff is related to #50, and it will be solved that.

**Comment by jpahullo** [comment]
If it works, I think this issue can be closed.

**Comment by jpahullo** [comment]
Good effort @ndunand !!!

**Comment by ndunand** [comment]
alright
