### ISSUE TITLE
Error writing to database - Duplicate Entry for key 'mdl_blockilpuserstat_use_uix'

### ISSUE THREAD

**Issue by Teylar** [ndunand/moodle-tool_mergeusers#109]
Hi,

We are using Moodle 2.7.8+ and having installed the plugin, I've tested on a few records and received the following error for both.

Merged «13100498» (user ID = 71819) into «13101116» (user ID = 71596)

For further reference, these results are recorded in the log id 2.
Some error occurred:

Exception thrown when merging: 'Error writing to database".
Duplicate entry '71596' for key 'mdl_blocilpuserstat_use_uix'
Trace:
#0 /var/www/html/moodle27/lib/dml/mysqli_native_moodle_database.php(974): moodle_database->query_end(false)
#1 /var/www/html/moodle27/admin/tool/mergeusers/lib/table/generictablemerger.php(225): mysqli_native_moodle_database->execute('UPDATE mdl_bloc...')
#2 /var/www/html/moodle27/admin/tool/mergeusers/lib/table/generictablemerger.php(80): GenericTableMerger->updateRecords(Array, Array, 'user_id', Array, Array)
#3 /var/www/html/moodle27/admin/tool/mergeusers/lib/mergeusertool.php(281): GenericTableMerger->merge(Array, Array, Array)
#4 /var/www/html/moodle27/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('71596', '71819')
#5 /var/www/html/moodle27/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('71596', '71819')
#6 {main}

Merge failed!
Your database engine supports transactions. Therefore, the whole current transaction has been rolled back and no modification has been made to your database.

Can you advise how to resolve this?

Kind regards

Wendy Hoskins

**Comment by ndunand** [comment]
Hi Wendy,

Thanks for reporting. The databse index `mdl_blocilpuserstat_use_uix` seems to belong to some third-party plugin. Do you have any idea as to which plugin this might refer to?

**Comment by Teylar** [comment]
Hi Nicholas

Thank you for the prompt reply

The index is part of block ILP

[http://moodle27dev.midkent.ac.uk/theme/image.php?theme=essentialmkc4&component=block_ilp&image=icon]ILP block
block_ilp

Additional

2013081502

Enabled


[cid:image002.png@01D168C5.3FD5D780]

Kind regards

Wendy Hoskins

Wendy Hoskins

ICT Technical Support Engineer

MidKent College
Medway Campus
Medway Road
Gillingham
Kent
ME7 1FN

________________________________

Telephone No.    : 01634  383000 Ext 3686  (Direct 01634 383686)
E-Mail Address    : Wendy.Hoskins@midkent.ac.uk<mailto:Wendy.Hoskins@midkent.ac.uk>
World Wide Web : www.midkent.ac.uk<http://www.midkent.ac.uk/>

Avoid delays by sending all job requests to the ICT Helpdesk, and not individual ICT staff

Queries regarding ICT jobs are welcome • ICT.Helpdesk@midkent.ac.uk<mailto:ICT.Helpdesk@midkent.ac.uk>
or ( Medway Ext. 3666. (Remember to quote the job number)

Any other feedback is always welcome • ICT.Feedback@midkent.ac.uk<mailto:ICT.Feedback@midkent.ac.uk>

**Comment by jpahullo** [comment]
Hi!

Could you show us which are the table and columns related to the index `mdl_blocilpuserstat_use_uix`?

This way, we will be able to give you the corresponding feedback.

Thanks!

Jordi

**Comment by Teylar** [comment]
Hi Jordi

Please see the screenshots below.  Hopefully this shows you what you need, but if you should require anything else, please let me know.


mdl_block_ilp_user_status table

[cid:image001.png@01D16996.476EA720]


mdl_blockilpuserstat_use_idx

[cid:image002.png@01D16996.476EA720]


Details from the mdl_block_ilp_user_status table for id 71596

[cid:image003.png@01D16996.979E2630]


Kind regards

Wendy


Wendy Hoskins

ICT Technical Support Engineer

MidKent College
Medway Campus
Medway Road
Gillingham
Kent
ME7 1FN

________________________________

Telephone No.    : 01634  383000 Ext 3686  (Direct 01634 383686)
E-Mail Address    : Wendy.Hoskins@midkent.ac.uk<mailto:Wendy.Hoskins@midkent.ac.uk>
World Wide Web : www.midkent.ac.uk<http://www.midkent.ac.uk/>

Avoid delays by sending all job requests to the ICT Helpdesk, and not individual ICT staff

Queries regarding ICT jobs are welcome • ICT.Helpdesk@midkent.ac.uk<mailto:ICT.Helpdesk@midkent.ac.uk>
or ( Medway Ext. 3666. (Remember to quote the job number)

Any other feedback is always welcome • ICT.Feedback@midkent.ac.uk<mailto:ICT.Feedback@midkent.ac.uk>

**Comment by jpahullo** [comment]
Hi!

For some reason, I cannot see the images so I cannot make any proper reply. Could you add into the github issue https://github.com/ndunand/moodle-tool_mergeusers/issues/109 directly? I suppose this way all we could see the attached images before.

Thank you in advance!

Jordi

**Comment by Teylar** [comment]
Hi Jordi

Attaching the images as requested :-)

Kind regards

Wendy

![mdl_block_ilp_user_status table](https://cloud.githubusercontent.com/assets/17271309/13117224/e8c87de6-d596-11e5-9185-e16f1817638e.png)
![mdl_blockilpuserstat_use_idx index](https://cloud.githubusercontent.com/assets/17271309/13117235/f0668cfa-d596-11e5-9d15-4b532bf3ecee.png)
![detail selection from mdl_block_ilp_user_status table](https://cloud.githubusercontent.com/assets/17271309/13117243/f7110242-d596-11e5-89f3-1dc735515ef5.png)

**Comment by jpahullo** [comment]
Hi!

You should overcome this problem by having your own `config/config.local.php` with the following content.

```
//config/config.local.php
return array(
 'compoundindexes' => array(
        'block_ilp_user_status' => array(
            'userfield' => array('user_id'),
            'otherfields' => array(),
        ),
    ),
 );
```

Note that if you already have this config.local.php file, just update it with appending this content:

```
        'block_ilp_user_status' => array(
            'userfield' => array('user_id'),
            'otherfields' => array(),
        ),
```

into the ` 'compoundindexes' => array(` section.

Always, always, always, try it first in pre-production environment and check the results.

Tell us if this solves your merging problem.

Thanks in advance!

Jordi

**Comment by danbuntu** [comment]
Hi

I've picked up on this job from Wendy.

I've applied the config change as noted above and I'm still getting the error:


`Exception thrown when merging: 'Error reading from database".
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM mdl_block_ilp_user_status WHERE user_id in (72000, 2000)' at line 1
Trace:
#0 /var/www/html/moodle27/lib/dml/mysqli_native_moodle_database.php(1080): moodle_database->query_end(false)
#1 /var/www/html/moodle27/admin/tool/mergeusers/lib/table/generictablemerger.php(122): mysqli_native_moodle_database->get_records_sql('SELECT id, user...')
#2 /var/www/html/moodle27/admin/tool/mergeusers/lib/table/generictablemerger.php(77): GenericTableMerger->mergeCompoundIndex(Array, 'user_id', Array, Array, Array, Array)
#3 /var/www/html/moodle27/admin/tool/mergeusers/lib/mergeusertool.php(288): GenericTableMerger->merge(Array, Array, Array)
#4 /var/www/html/moodle27/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('2000', '72000')
#5 /var/www/html/moodle27/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('2000', '72000')
#6 {main}

`

**Comment by jpahullo** [comment]
Hi!

This is a different error, regarding to the generation of the query. Let me make some checks and I'll be back.

Jordi

**Comment by jpahullo** [comment]
Hi!

Sorry for the inconvenience.

I now realize completely the problem and the solution proposed before do not solve your case. I assumed it incorrectly. Sorry about this.

To solve your case, we need to update the plugin to include your case, which should be something like this:

Context: There is NO compound index, but there exists a UNIQUE KEY over the user related field to update.

Procedure to be corrected:
1. Try to update the record related to the old user id, replacing it with the new user id.
1. If Exception is thrown, and by the context, there is no compound index, there will be an unique key over the user related field.
1. Then, remove a record related to the new user id. (By the context, it must be a unique key with a single column, so there will be only a record).
1. Then, update the record related to the old user id, replacing it with the new user id.

Is this correct? @ndunand, do you agree with the proposed solution? The code to update will be into the method https://github.com/ndunand/moodle-tool_mergeusers/blob/master/lib/table/generictablemerger.php#L211

By now, @danbuntu and @Teylar, you can revert the changes on the `config.local.php` file, since the change I proposed is not sufficient to solve your case. Sorry about that.

Thanks for reporting back the error. Thank you for your time. Thank you for all.

Jordi

**Comment by jpahullo** [comment]
Hi @ndunand 

I've pushed a PR for this issue. If you can make a peer-review and accept it if you consider it ok.

Thanks for your time!

Hugs!

Jordi

**Comment by jpahullo** [comment]
Hi! 

The master branch has the last changes, including a patch to treat your case. I've passed some local tests emulating your case and it worked perfectly. Please, try it and give feedback back. As always, better if you can try it in a test environment.

Thanks in advance!

Thanks @ndunand for your time reviewing code and accepting the merge request. Hoping you are ok.

Kind regards,

Jordi

**Comment by jpahullo** [comment]
If you find this issue is solved, please, comment and close it.

Thanks!
