### ISSUE TITLE
Using old Event 1 API

### ISSUE THREAD

**Issue by nitro2010** [ndunand/moodle-tool_mergeusers#113]
The following plugins in your system are using Events 1 API deprecated handlers: 'local_obf, mod_booking, enrol_elediacohortgreeting, **tool_mergeusers**, local_welcome'. Please, update them to use Events 2 API. See https://docs.moodle.org/dev/Event_2#Event_dispatching_and_observers.

**Comment by jpahullo** [comment]
Hi!

Thanks for reporting this issue.

We'll face it as soon as possible.

Jordi

**Comment by jpahullo** [comment]
Sorry by my last comment. 

The master branch is already compatible with Events 2 API from Moodle.

Please, install it from github repository and give us feedback back. If all is ok, please close this issue.

Thansk for your time,

Jordi

**Comment by adigitalife** [comment]
I believe I have the current master, version 2016051800.  Unfortunately, I'm still seeing the Events 1 API message.

**Comment by nadavkav** [comment]
I am experiencing similar warnings, on a Moodle 3.1 + tool_mergeusers (master branch)

**Comment by jimitodd** [comment]
Me too.
Is there a date when the version will be updated.

**Comment by jpahullo** [comment]
Hi all!

Thank you for your comments.

Could you report which Moodle version you have, and where (which Moodle URL) can you see this advise that those plugins were using an old Event API?

I have it installed on a Moodle 3.0.4 and there is no warning on that respect.

Any information will help us.

Jordi

**Comment by ndunand** [comment]
Hi @jpahullo,

This is displayed on the main admin page of the Moodle site, i.e. `/admin/index.php`.

Is think there is confusion because this was addressed (merged) in #115, but not yet released on Moodle.org.

**Comment by ndunand** [comment]
@jpahullo Should I release now or is there any other fixes we can push before?

**Comment by jpahullo** [comment]
Ohhh... Yes, I think so. This is why I always state about using the last version of the master branch.

Plese, @ndunand, go ahead and release a new version. It should support 3.1 too if nothing is reported.

Thank you for your time and sorry for this late answer.

Jordi

**Comment by ndunand** [comment]
OK, thanks Jordi, releasing new version now.
