### ISSUE TITLE
tool_mergeusers - Save selection for one user - stack trace

### ISSUE THREAD

**Issue by kirstymeredith** [ndunand/moodle-tool_mergeusers#116]
Hi 
![save_selection_1_user_before](https://cloud.githubusercontent.com/assets/22369427/18746557/f7c2649a-80bf-11e6-9695-1eb5bc1983c2.png)
![save_selection_1_user_to_keep_stack_trace](https://cloud.githubusercontent.com/assets/22369427/18746555/f7c18cc8-80bf-11e6-8341-c24fc69bafc9.png)
![save_selection_1_user_to_remove_stack_trace](https://cloud.githubusercontent.com/assets/22369427/18746556/f7c24ec4-80bf-11e6-95b9-b721873fc9fe.png)

I am experiencing this when I save the selection to keep or remove 1 user and get the following stack trace above the page (also included in the attached screen shots):

( ! ) Notice: Trying to get property of non-object in /u0/webroot/virtual/planinternational.dev.synergy-learning.com/www/admin/tool/mergeusers/lib/userreviewtable.php on line 100
Call Stack
# Time    Memory  Function    Location

1   0.0010  293048  {main}( )   .../index.php:0
2   5.7536  70350552    tool_mergeusers_renderer->index_page( ) .../index.php:110
3   6.1504  71239536    tool_mergeusers_renderer->render_user_review_table( )   .../renderer.php:127
4   6.1510  71270680    UserReviewTable->__construct( ) .../renderer.php:152
5   6.1511  71271696    UserReviewTable->buildtable( )  .../userreviewtable.php:85

Is this expected to be handled this way, whenever only 1 user is saved in selection (i.e.  should a prompt not be made for a another user to be kept/removed as appropriate?)

Thanks!

Kirsty

**Comment by ndunand** [comment]
Hi,

Thanks for reporting this. This does not affect how the plugin works but indeed shows a small flaw in the code. This will be fixed.

Now, answering your question. Yes, this is (apart from the red warning) is how it should behave. After having selected the first user to either keep or remove, you're now supposed to make a new search for the 2nd user account. Once you've selected both the user to keep and the user to remove, you'll have the opportunity to merge them.

**Comment by jpahullo** [comment]
Hi all!

I applied this code for activate debugging into Moodle, into the file config.php and after the line of setup.php:

```
require_once(dirname(__FILE__) . '/lib/setup.php');

// just for debugging
ini_set('display_errors', true);
ini_set('error_reporting', E_ALL | E_STRICT);
$CFG->debug = E_ALL | E_STRICT;
// end just for debugging
```

and I don't see any warning or error. Which version do you use in your production environment? Are you using the latest version of the master branch of this repo?

Thanks for helping us improve this plugin.

Jordi

**Comment by jpahullo** [comment]
This warning was already addressed in this plugin. Closing issue.

Thanks for the feedback.
