### ISSUE TITLE
Merge Accounts plugin not working

### ISSUE THREAD

**Issue by petec-i2isys** [ndunand/moodle-tool_mergeusers#122]
Hi all,
I installed the merge accounts plugin successfully, but when I go to use it these two message appear:

Warning: include(/home/i2ielear/public_html/admin/tool/qeupgradehelper/version.php): failed to open stream: No such file or directory in /home/i2ielear/public_html/lib/classes/plugin_manager.php on line 318

Warning: include(): Failed opening '/home/i2ielear/public_html/admin/tool/qeupgradehelper/version.php' for inclusion (include_path='/home/i2ielear/public_html/lib/pear:.:/usr/local/php55/pear') in /home/i2ielear/public_html/lib/classes/plugin_manager.php on line 318

Does anyone know how to help?

**Comment by jpahullo** [comment]
Please, refer to your own Moodle instance and administrator. The error is related to another plugin that seems does not exist: "admin/tool/qeupgradehelper/". It is not related to our plugin.

Thanks for reporting.
