### ISSUE TITLE
Merge Error

### ISSUE THREAD

**Issue by nfrederickx** [ndunand/moodle-tool_mergeusers#123]
Hello,

I receive this error when trying to merge an account:
`Merged «jbuyze@itg.be» (user ID = 1570) into «jbuyze» (user ID = 1768)

For further reference, these results are recorded in the log id 2.
Some error occurred:

Exception thrown when merging: 'Error reading from database".
Unknown column 'id' in 'field list'
Trace:
#0 D:\Systemdata\Websites\campus.itg.be\lib\dml\mysqli_native_moodle_database.php(1175): moodle_database->query_end(false)
#1 D:\Systemdata\Websites\campus.itg.be\admin\tool\mergeusers\lib\table\generictablemerger.php(75): mysqli_native_moodle_database->get_records_sql('SELECT id FROM ...')
#2 D:\Systemdata\Websites\campus.itg.be\admin\tool\mergeusers\lib\mergeusertool.php(288): GenericTableMerger->merge(Array, Array, Array)
#3 D:\Systemdata\Websites\campus.itg.be\admin\tool\mergeusers\lib\mergeusertool.php(216): MergeUserTool->_merge('1768', '1570')
#4 D:\Systemdata\Websites\campus.itg.be\admin\tool\mergeusers\index.php(135): MergeUserTool->merge('1768', '1570')
#5 {main}

Merge failed!
Your database engine supports transactions. Therefore, the whole current transaction has been rolled back and no modification has been made to your database.`

We have the latest merge plugin (1.13 for Moodle 2.2-3.2 (Build: 2016120100)
2016113000) and Moodle (Moodle 3.2.2 (Build: 20170313))

I tried with "transactions allowed" and without, but result stays the same.
![2017-05-11_16h19_57](https://cloud.githubusercontent.com/assets/28628271/25954214/d85d46c2-3665-11e7-91f0-8dc780e52ba6.png)

Any ideas on how to fix this?
Thank you for your help!

**Comment by jpahullo** [comment]
Hi!

Thanks for reporting.

This kind of error appears when you have some custom, third-party plugin, which does not follow the Moodle recommendations in the database design. In particular, this plugin does not have a column with name `id`.

You need to find it and exclude it from being processed, or define the compound key.

Last but not least, are you using the last version of the plugin? Be sure of that.

However, if you cannot afford running it, please, come back with more details on the database table producing this error.

**Comment by jpahullo** [comment]
By now, I'm closing this issue. You can take more reference at issue #128 for how to set up.
Thanks for reporting.
