### ISSUE TITLE
In AMOS, tool exists only up to version 2.8

### ISSUE THREAD

**Issue by lucaboesch** [ndunand/moodle-tool_mergeusers#124]
Dear Nicolas.
I've tried to translate your tool to german properly, but in AMOS the strings seem to be stuck on version 2.8.
It would be great if you could do something about it. I'm planning to use it myself and to properly translate it to german.
All the best,
Luca

**Comment by ndunand** [comment]
Hi Luca,

Thanks for your interest. Indeed there is something with this plugin on AMOS. I have contacted the AMOS team and hope to have this resolved soon.

In the meantime, you could write your own (local) translation (i.e. in `/lang/de`) and upload it to AMOS later on, when things are fixed.

**Comment by ndunand** [comment]
Should be fixed now
