### ISSUE TITLE
Does not run on 3.3 install

### ISSUE THREAD

**Issue by peachmom** [ndunand/moodle-tool_mergeusers#125]
Using Moodle 3.3, installation went fine, but when I go to Site Admin->Users->Accounts->Merge User Accounts->Merge User Accounts it fails with the following errors:

Notice: Undefined property: stdClass::$dirroot in /var/www/html/admin/tool/mergeusers/log.php on line 34

Warning: require_once(/lib/adminlib.php): failed to open stream: No such file or directory in /var/www/html/admin/tool/mergeusers/log.php on line 34

Fatal error: require_once(): Failed opening required '/lib/adminlib.php' (include_path='/var/www/html/lib/pear:.:/usr/share/pear:/usr/share/php') in /var/www/html/admin/tool/mergeusers/log.php on line 34

Its weird, it looks like the $CFG object is not being loaded properly.

**Comment by peachmom** [comment]
Okay, got past those errors by changing the "require('../../../config.php');" line to "require_once('../../../config.php');" in the log.php file. However, now when I click on "Merge User Accounts", it tells me a required parameter (id) is missing.

**Comment by jpahullo** [comment]
Thanks for reporting.
We'll keep an eye on this.

**Comment by jpahullo** [comment]
does this apply yet?

However, consider upgrading the Moodle and plugin version to latest. 

This issue is related to M3.3, and the latest plugin release we support is from M3.4 onwards.

Thanks for the feedback.
