### ISSUE TITLE
Unknown column 'id' in 'field list'

### ISSUE THREAD

**Issue by rtn** [ndunand/moodle-tool_mergeusers#128]
Merged «rtnalm@lsit.ucsb.edu.1371756546» (user ID = 22676) into «ratana» (user ID = 29798)

For further reference, these results are recorded in the log id 1.
Some error occurred:

Exception thrown when merging: 'Error reading from database".
Unknown column 'id' in 'field list'
Trace:
#0 /var/www/ssl/rlim/31/lib/dml/mysqli_native_moodle_database.php(1175): moodle_database->query_end(false)
#1 /var/www/ssl/rlim/31/admin/tool/mergeusers/lib/table/generictablemerger.php(75): mysqli_native_moodle_database->get_records_sql('SELECT id FROM ...')
#2 /var/www/ssl/rlim/31/admin/tool/mergeusers/lib/mergeusertool.php(288): GenericTableMerger->merge(Array, Array, Array)
#3 /var/www/ssl/rlim/31/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('29798', '22676')
#4 /var/www/ssl/rlim/31/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('29798', '22676')
#5 {main}

**Comment by jpahullo** [comment]
Hi!

It is a usual error reported when you have some third party plugin or customization on your Moodle instance. This error appears when there exists at least a database table not following the Moodle standards, mainly having a column named "id".

You or your administrator should look at it and exclude this table from being considered (like those under https://github.com/ndunand/moodle-tool_mergeusers/blob/master/config/config.php#L42). 

One way of doing so is just have a customized `config/config.local.php` with the following structure:

```
<?php

return array(
    'exceptions' => array(
        'the_name_of_the_problematic_table`,
    ),
);
```

Once set up, this plugin will merge config.php and your config.local.php configurations before processing any new merging. If you already have the file config.local.php, just update it with the above structure.

Doing so, you will be able to merge users, but the content of that table will remain untouched.

Let us know how it was.

Regards,

Jordi

**Comment by jpahullo** [comment]
I'm closing this issue due to its inactivity. Thanks.
