### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by spallison** [ndunand/moodle-tool_mergeusers#130]
Fatal error: Class '\tool_mergeusers\event\user_merged_success' not found in E:\moodle\admin\tool\mergeusers\lib\mergeusertool.php on line 221 

Moodle 2.5.9 (Build: 20141110)

**Comment by jpahullo** [comment]
Hi Simon!

Thanks for the feedback. There is a point to consider on Moodle, that classes autoloading (https://docs.moodle.org/dev/Automatic_class_loading) is available only from Moodle 2.6 and on. If you are using the last version of this plugin, this will not work properly. Consider using an older version or using a newer Moodle version.

Thanks for sharing.

Jordi

**Comment by jpahullo** [comment]
I propose closing this issue @ndunand, if @spallison agrees.
