### ISSUE TITLE
M3.5 and GDPR

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#143]
Provided feedback on Moodle Plugins page:

===== 

By https://moodle.org/user/view.php?id=1207459&course=1

====

Moodle 3.5 compatible and no privacy provider?

As a result the phpunit tests fail:

provider_testcase::test_all_providers_compliant with data set "tool_mergeusers" ('tool_mergeusers', 'tool_mergeusers\privacy\provider')
Failed asserting that false is true.

privacy/tests/provider_test.php:178
ips/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
vendor/bin/phpunit provider_testcase privacy/tests/provider_test.php

**Comment by jpahullo** [comment]
Meanwhile this is under developing, I placed a disclaimer on the the plugin's description at https://moodle.org/plugins/tool_mergeusers.

Once we successfully face it, we will remove that disclaimer.

**Comment by danmarsden** [comment]
I think you can probably just implement the null provider. This plugin doesn't store any user data.

**Comment by ndunand** [comment]
I have implemented null_provider as this plugin does not store any data. This is in commit 0b91627

**Comment by ndunand** [comment]
@jpahullo thanks for documenting this – I've now removed the disclaimer as the new version implementing this has been released on moodle.org

**Comment by jpahullo** [comment]
wow!!! Thank you @ndunand and @danmarsden for your help!

**Comment by jpahullo** [comment]
Just a doubt: storing user.id on the log of the merge operation, it does not make this plugin store personal data, isn't it?

**Comment by danmarsden** [comment]
I wouldn't think so - but it is probably worth implementing some form of clean up task to delete the data from that table after a set time period.
