### ISSUE TITLE
Support for Oracle database

### ISSUE THREAD

**Issue by hmgp** [ndunand/moodle-tool_mergeusers#153]
Since issue #152 was overcome, but things don't work, I was asked to open this new issue.

This issue is to try to make this plugin work with an Oracle database.

As stated in issue #152 nothing happens in a Oracle database.
I get information that the operation reached the end without errors, but I get no queries in the log, and the only modification is that the user to be suspended is suspended. No grades, no status, nothing get's passed to the new user.

One symptom to make note is that when the log is supposed to show the selects made on the database, I get none. Nothing is showed.

If you have any place to start looking, please tell me, I will be glad to test it.

Thank you.

**Comment by jpahullo** [comment]
This is solved with PR #154
