### ISSUE TITLE
Wrong entries deleted in case of conflict

### ISSUE THREAD

**Issue by t-schroeder** [ndunand/moodle-tool_mergeusers#168]
While testing I noticed that "uniquekeynewidtomaintain" is always read as false regardless what value you set it to.

**Comment by t-schroeder** [comment]
The consequence of this bug is: when you have a table where the userid column is unique and both users have an entry in that table, the entry of the user you want to keep gets deleted.

**Comment by jpahullo** [comment]
Fixed! Thanks!
