### ISSUE TITLE
Radio buttons for User to keep/User to remove not showing up - Moodle 3.4.9/Totara 13

### ISSUE THREAD

**Issue by mominzahid** [ndunand/moodle-tool_mergeusers#185]
I'm running Totara 13 which is based on Moodle 3.4.9 (Build: 20190513)

I've attached a screenshot of the issue. The radio buttons are missing. They are not getting added to the DOM. Anyone else running into this issue? Can the developers offer any insight on how it can be fixed?  

![image](https://user-images.githubusercontent.com/10189301/104508201-7ffe2f80-55ad-11eb-9145-de999d148649.png)

**Comment by junnever** [comment]
Did you resolve this?

**Comment by jpahullo** [comment]
Hi @junnever,

I have no news about this. @mominzahid closed this issue by his own. Nowadays Moodle 3.4 is not maintained anymore. Maybe in newer releases of Totara it works properly.

Thanks for contacting back.

Jordi

**Comment by junnever** [comment]
We figured this out a few minutes after posting the question.   Clicking the  'Disable consistent cleaning' option in Admin>Security fixed it.  (Totara 17)

**Comment by jpahullo** [comment]
Oh! Thanks for the feedback. Since there is a core option to allow them watching, I will lock this conversation as an additional ingredient of "resolved".

Thanks @junnever.

Jordi
