### ISSUE TITLE
automate Moodle Plugin publication with github actions

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#193]
New github action posted by Moodle HQ at https://github.com/moodlehq/moodle-plugin-release allows to publish automatically into Moodle Plugins directory.

Adapt this plugin to let it work.

**Comment by ndunand** [comment]
Hi Jordi,

I had put the credentials in this repo but removed them after today’s enhancements to the workflow from David. 

I haven’t had time to look into it but will next week.

**Comment by jpahullo** [comment]
Don’t worry Nicolas. I’m just recording things to do.
