### ISSUE TITLE
"Did you remember to..."  PHP notices

### ISSUE THREAD

**Issue by luisdev** [ndunand/moodle-tool_mergeusers#21]
I've installed '$plugin->version = 2014011012' of this Merge Users plugin on my Moodle 2.5.3+ (Build: 20131129) test server which is on a MSSQL 2008 R2, Windows Server 2008 R2, IIS 7 and PHP 5.3.8, SRLSRV platform. When the Moodle Debug messages option is set to 'DEVELOPER' and debugdisplay is set to 'Yes' I get the following debug messages when I open the Site administration / Users / Accounts / Merge user accounts / Merge user accounts page. Are these "Duplicate value ... found in column 'table_catalog'" messages something I should worry about?

The messages are:

Did you remember to call setType() for 'oldusergroup[olduserid]'? Defaulting to PARAM_RAW cleaning.?line 1334 of \lib\formslib.php: call to debugging()
?line 281 of \lib\formslib.php: call to moodleform->detectMissingSetType()
?line 202 of \lib\formslib.php: call to moodleform->_process_submission()
?line 56 of \admin\tool\mergeusers\index.php: call to moodleform->moodleform()

Did you remember to call setType() for 'newusergroup[newuserid]'? Defaulting to PARAM_RAW cleaning.?line 1334 of \lib\formslib.php: call to debugging()
?line 281 of \lib\formslib.php: call to moodleform->detectMissingSetType()
?line 202 of \lib\formslib.php: call to moodleform->_process_submission()
?line 56 of \admin\tool\mergeusers\index.php: call to moodleform->moodleform()

Did you remember to make the first column something unique in your call to get_records? Duplicate value 'MyMoodleDatabaseName' found in column 'table_catalog'.?line 845 of \lib\dml\sqlsrv_native_moodle_database.php: call to debugging()
?line 607 of \admin\tool\mergeusers\lib\mergeusertool.php: call to sqlsrv_native_moodle_database->get_records_sql()
?line 323 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->getCurrentUserFieldNames()
?line 153 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->init()
?line 61 of \admin\tool\mergeusers\index.php: call to MergeUserTool->__construct()

Did you remember to make the first column something unique in your call to get_records? Duplicate value 'MyMoodleDatabaseName' found in column 'table_catalog'.?line 845 of \lib\dml\sqlsrv_native_moodle_database.php: call to debugging()
?line 607 of \admin\tool\mergeusers\lib\mergeusertool.php: call to sqlsrv_native_moodle_database->get_records_sql()
?line 323 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->getCurrentUserFieldNames()
?line 153 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->init()
?line 61 of \admin\tool\mergeusers\index.php: call to MergeUserTool->__construct()

Did you remember to make the first column something unique in your call to get_records? Duplicate value 'MyMoodleDatabaseName' found in column 'table_catalog'.?line 845 of \lib\dml\sqlsrv_native_moodle_database.php: call to debugging()
?line 607 of \admin\tool\mergeusers\lib\mergeusertool.php: call to sqlsrv_native_moodle_database->get_records_sql()
?line 323 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->getCurrentUserFieldNames()
?line 153 of \admin\tool\mergeusers\lib\mergeusertool.php: call to MergeUserTool->init()
?line 61 of \admin\tool\mergeusers\index.php: call to MergeUserTool->__construct()

**Comment by ndunand** [comment]
@luisdev could you please provide somme feedback on this? Is this issue still relevant?

**Comment by luisdev** [comment]
Ok, I will retest the patch and report back.

**Comment by jpahullo** [comment]
I think we can close this issue now, since we removed our database specific SQLs and rely on the `$DB` to get the list of tables. We do not reinvent the wheel any more ;-)
