### ISSUE TITLE
Cannot duplicate quiz

### ISSUE THREAD

**Issue by scarpio97** [ndunand/moodle-tool_mergeusers#212]
Good morning everyone,

Moodle is not allowing duplicate quizzes. This seems to be caused by the amount  of questions (and question banks!) attached to the quiz.

When trying, it stays loading until the error "Undefined"

How can we solve it?

There is a resource limitation to duplicate quizzes, for example from php?

Thank you very much and greetings!

**Comment by jpahullo** [comment]
Hi @scarpio97 ,

It seems you mismatch the plugin you are referring to. You're talking about quizzes and questions, and this plugin is nothing about managing those items.

Thanks anyway for contacting.
