### ISSUE TITLE
4.0 support?

### ISSUE THREAD

**Issue by durzo** [ndunand/moodle-tool_mergeusers#215]
Is this plugin 4.0 compatible?

**Comment by jpahullo** [comment]
We haven’t provided version for 4.*, but according to current stats https://moodle.org/plugins/tool_mergeusers/stats there are hundreds of sites using it on Moodle 4.0 onwards. 

Sooner than later, we will provide the plugin versioned for Moodle 4.*. 

If you find anything about it, please report it here as a new issue. 

Thanks for your interest. 

Jordi
