### ISSUE TITLE
Generic class name used in config.php

### ISSUE THREAD

**Issue by danmarsden** [ndunand/moodle-tool_mergeusers#66]
admin/tool/mergeusers/lib/config.php defines the class "Config" - this is way too generic and could conflict with a range of different things - it is also confusing as Moodle has it's own handling of generic config values.

This class should be renamed to something specific to tool_mergeusers - maybe something like:
class tool_mergeusers_config()

**Comment by jpahullo** [comment]
This issue can be closed @ndunand :yum:

**Comment by ndunand** [comment]
Right, thanks @jpahullo for keeping up with things 😊
