### ISSUE TITLE
settings.php 

### ISSUE THREAD

**Issue by danmarsden** [ndunand/moodle-tool_mergeusers#67]
in settings.php this call is made before the check to $hassiteconfig.
require_once **DIR** . '/lib/autoload.php';

This function seems to do a bit of work and loads a lot of classes that don't appear to be needed within settings.php

settings.php is called on almost every Moodle page load so should be optimised to do as little work as possible.

Every time this is called:
MergeUserTool::transactionsSupported()

mergeusertool calls _construct and makes a sql query for every table that exists in the Moodle database. This causes significant unnecessary load on the server when $hassiteconfig = true. if you want to use trasactionsupported() it should sit outside the class and be usable without needing to make all those db calls.

**Comment by jpahullo** [comment]
@danmarsden , please, you catched my attention when said "removing the 450 sql queries". Which tool do you use for debugging the number of queries to the database? I think it will be very useful for me too in my job.

Thanks in advance!

Jordi

**Comment by danmarsden** [comment]
I'm pretty sure that number came from me reading the code and knowing how many tables there are in the standard moodle site (not sure how I ended up with 450 - I'd need to go look at the old code again) - it looks like this is no longer an issue in the newer code - a much better/faster way of checking for transaction support has been implemented.

There are a range of ways to debug sql queries - Moodle has support built-in for some techniques such as:
 //     $CFG->logsql = true; 

Different database types have their own built-in support for logging queries - Mysql has:
http://dev.mysql.com/doc/refman/5.0/en/slow-query-log.html

Postgres has other techniques too - we've used this script in the past to parse all logs to find slow queries:
http://git.catalyst.net.nz/gw?p=pgtools.git;a=blob_plain;f=scripts/pg-log-process.pl;hb=refs/heads/pg-log-process-multidb

**Comment by danmarsden** [comment]
I forgot - core sql log handling changed in newer versions - check this out:
https://moodle.org/mod/forum/discuss.php?d=281324#p1208242

**Comment by jpahullo** [comment]
Many thanks!!

I'll check all this.

Thanks for collaborating in this plugin too.

Jordi

**Comment by jpahullo** [comment]
In local instance, M3.7, I can see:

![image](https://user-images.githubusercontent.com/2048296/63158629-f219c000-c019-11e9-82c6-bd40bdee18f7.png)

with the latest version of the plugin 1.20.

**Comment by jpahullo** [comment]
with the improved implementation:

![image](https://user-images.githubusercontent.com/2048296/63160455-1aa3b900-c01e-11e9-9168-dd88c2ec022c.png)
it seems that there is no so much improvement.

**Comment by jpahullo** [comment]
just one file prevented to load after all.

**Comment by jpahullo** [comment]
I will leave it as it was, with the autoloaders. However, I add some functions to clean up settings.php for a better readability.

**Comment by jpahullo** [comment]
related PR #164

**Comment by jpahullo** [comment]
In Moodle 3.7, I can see just 90/0 or 90/1 read/writes. So much better than in the Moodle version we saw in the prior comments with 450 db operations.

**Comment by jpahullo** [comment]
Indeed, it is not a plugin-related improvement, but a Moodle improvement.

**Comment by jpahullo** [comment]
done
