### ISSUE TITLE
Error: Database type mariadb not supported.

### ISSUE THREAD

**Issue by bozicm** [ndunand/moodle-tool_mergeusers#74]
MariaDB is actually supported since 2.6: https://docs.moodle.org/26/en/MariaDB

It would be good to have 'mariadb' string included in database check by default.

**Comment by jharej** [comment]
Hi, can we expect that this issue will be solved? We would realy need this tool on our site.

**Comment by jpahullo** [comment]
Hi @jharej ,

We'll try to get into master branch for next week.

Hoping this helps,

Jordi

**Comment by jpahullo** [comment]
Hi!

I've created a PR. Things are going on.

Jordi

**Comment by ndunand** [comment]
Great, thanks @jpahullo. Merging now.
