### ISSUE TITLE
deleting users with same badge

### ISSUE THREAD

**Issue by jharej** [ndunand/moodle-tool_mergeusers#80]
If I try to merge two users that have same/equal badge, I get the error

Duplicate entry '62-78146' for key 'mdl_badgissu_baduse_uix'

that is reasonable response as one badge can not be issued more than once to one user. Can some sort of check in this direction be added?

**Comment by jpahullo** [comment]
Hi!
Since badges are related to specific users (name, email, etc), even they are the same person, how do you think we should address this issue? Just removing the badge from the user to be removed? 

I think it is more than correct, however, I would apreciate your opinion.

Thanks in advance!

Jordi

**Comment by jharej** [comment]
Yes, I think that this is the only corect solution. Probably it would be wise to write this specific issue in read.me or somewhere else.

**Comment by romancuk** [comment]
I'm also interested in this issue.

**Comment by jpahullo** [comment]
It is already merged into the master branch. It should work. However, could you check that it is working as expected please?

Thanks in advance.

**Comment by romancuk** [comment]
@jpahullo 

Tested in testing environment. It looks that merging works OK. Also no side effect to Moodle was detected.

Will test in production environment and let you know.

**Comment by jpahullo** [comment]
Excellent. We expected nothing but exactly that: working ok :smile:

**Comment by ndunand** [comment]
Great, thanks @romancuk for reporting back. And thanks again @jpahullo for your valuable contribution.
