### ISSUE TITLE
don't list inactive accounts

### ISSUE THREAD

**Issue by jharej** [ndunand/moodle-tool_mergeusers#85]
I suggest that inactive accounts don't get listed when searching accounts to be merged. It's annoying, especially when the same person has more than two accounts and the same search has to be made more than once.

**Comment by luisdev** [comment]
My view is the opposite - I DO want to see inactive accounts.
Perhaps this could be a configurable option on an Settings page?

**Comment by jpahullo** [comment]
My question is: how do we know if a user was already merged?

Just because, by default, we mark the source user as "suspended", even though it is also configurable by the plugin settings and may be disabled.

Therefore, we can mark suspended users as by not allowing them to be selected from the list of suitable accounts to be merged.

However, maybe we want to choose a "suspended" user to be reenabled again.

It is not clear at all for me that this request is going to be applicable.

Jordi

**Comment by luisdev** [comment]
How do we know if a user was already merged? I presume the only record of a merge is the info that gets written to the merge log when a merge is done. But I don't think you can rely on the merge logs for that kind of info (what if the logs get purged?) Other than the logs, there is no other indicator of the merged status anywhere, is there?

Does it actually matter if any of the profiles is suspended when you do a merge? The main purpose of the plugin is to move the user activity data from the "User ID to be removed" profile to the "User ID to be kept" profile. Perhaps the only check the plugin should do is check if the selected "User ID to be kept" is already suspended. If it is then stop the merge and display a warning that the "User ID to be kept" profile cannot be suspended. I'm assuming that you would never want the "User ID to be kept" profile to be suspended after the merge. Am I correct? But if the "User ID to be removed" is already suspended BEFORE the merge is done, it does not matter, does it? You still want to move the user data from the "User ID to be removed" profile to the "User ID to be kept" profile, regardless of whether the "User ID to be removed" profile is already suspended or not.

If an admin wants to re-enable a suspended user then I think that must be done in the user profile settings (/user/editadvanced.php), not from this mergeusers plugin.

**Comment by ndunand** [comment]
Couldn't we simply display suspended users grayed out in the results list? Just the same as on Moodle's core Users > Accounts > Browse page. Then it would be up to the admin (or merger) to figure up what to do.

**Comment by jpahullo** [comment]
My friends:

1. Do we really need to make something different with suspended/merged users into the GUI for merging users? That is, do we need to include this issue into the plugin? Maybe not.
2. If so, I think the best option is to just show suspended users in a different way.

Jordi

**Comment by ndunand** [comment]
I agree with Jordi, we need a minimalistic approach here. How about having the same behaviour as the Browse users, i.e. simply add a `usersuspended` CSS class to those users in the listing:

    --- a/admin/tool/mergeusers/lib/userselecttable.php
    +++ b/admin/tool/mergeusers/lib/userselecttable.php
    @@ -95,12 +95,13 @@ class UserSelectTable extends html_table implements renderable
 
             foreach ($users as $userid => $user) {
                 $row = array();
    +            $spanclass = ($user->suspended) ? ('usersuspended') : ('');
                 $row[] = html_writer::empty_tag('input', array('type' => 'radio', 'name' => 'olduser', 'value' => $userid, 'id' => 'olduser' . $userid));
                 $row[] = html_writer::empty_tag('input', array('type' => 'radio', 'name' => 'newuser', 'value' => $userid, 'id' => 'newuser' . $userid));
    -            $row[] = $user->id;
    -            $row[] = $this->renderer->show_user($user->id, $user);
    -            $row[] = $user->email;
    -            $row[] = $user->idnumber;
    +            $row[] = html_writer::span($user->id, $spanclass);
    +            $row[] = html_writer::span($this->renderer->show_user($user->id, $user), $spanclass);
    +            $row[] = html_writer::span($user->email, $spanclass);
    +            $row[] = html_writer::span($user->idnumber, $spanclass);
                 $this->data[] = $row;
             }
         }

**Comment by jpahullo** [comment]
we'll take a look this way, so.

**Comment by ndunand** [comment]
If you agree @jpahullo , I'll just push this commit...

**Comment by jpahullo** [comment]
oh! go ahead @ndunand ! Thanks a lot!

**Comment by ndunand** [comment]
Okay, addressed in bc1cf41

**Comment by jpahullo** [comment]
perfect!

**Comment by jharej** [comment]
hi,

i vote for this solution.

bye

2015-02-23 13:05 GMT+01:00 Nicolas Dunand <notifications@github.com>:

> I agree with Jordi, we need a minimalistic approach here. How about having
> the same behaviour as the Browse users, i.e. simply add a usersuspended
> CSS class to those users in the listing:
>
> --- a/admin/tool/mergeusers/lib/userselecttable.php
> +++ b/admin/tool/mergeusers/lib/userselecttable.php
> @@ -95,12 +95,13 @@ class UserSelectTable extends html_table implements renderable
>
>          foreach ($users as $userid => $user) {
>              $row = array();
> +            $spanclass = ($user->suspended) ? ('usersuspended') : ('');
>              $row[] = html_writer::empty_tag('input', array('type' => 'radio', 'name' => 'olduser', 'value' => $userid, 'id' => 'olduser' . $userid));
>              $row[] = html_writer::empty_tag('input', array('type' => 'radio', 'name' => 'newuser', 'value' => $userid, 'id' => 'newuser' . $userid));
> -            $row[] = $user->id;
> -            $row[] = $this->renderer->show_user($user->id, $user);
> -            $row[] = $user->email;
> -            $row[] = $user->idnumber;
> +            $row[] = html_writer::span($user->id, $spanclass);
> +            $row[] = html_writer::span($this->renderer->show_user($user->id, $user), $spanclass);
> +            $row[] = html_writer::span($user->email, $spanclass);
> +            $row[] = html_writer::span($user->idnumber, $spanclass);
>              $this->data[] = $row;
>          }
>      }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndunand/moodle-tool_mergeusers/issues/85#issuecomment-75530533>
> .
>



-- 
=======================
Janko Harej
ŠC Nova Gorica

**Comment by ndunand** [comment]
Hi @jharej , thanks for your feedback. The latest version available here addresses this.

**Comment by luisdev** [comment]
Perfect, thanks.
