### ISSUE TITLE
duplicate entry - assigments

### ISSUE THREAD

**Issue by jharej** [ndunand/moodle-tool_mergeusers#86]
When mergin two account I got Duplicate entry '2592-37258-0' for key 'mdl_assigrad_assuseatt_uix'

mdl_assigrad_assuseatt_uix is an index in table mdl_assign_grades, UNIQUE KEY `mdl_assigrad_assuseatt_uix` (`assignment`,`userid`,`attemptnumber`). 

As I understand it, it is not possible for one person to get more than one grade for the same attempt on same assignment. I suggest that in this case the newer grade remains.

**Comment by jpahullo** [comment]
Hi!

Thanks for reporting!!!

I'll do a PR for this issue, since it is a database table from Moodle core.

Jordi

**Comment by jpahullo** [comment]
Working on this... :hourglass_flowing_sand:

**Comment by ndunand** [comment]
Alright, meanwhile I just committed some very small commits: 
 - 2ca4e5b and 06a7886 to fix #61 
 - 3c4b335 for new release version number

**Comment by jpahullo** [comment]
Awesome!

**Comment by jpahullo** [comment]
PR done!
