### ISSUE TITLE
config.php: mixed old and new formats

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#88]
In the last release 1.10.1 there is a mixed formats for compound indexes, due to old PR.

**Comment by ndunand** [comment]
Ouch. Does fd651ba fix this correctly?

**Comment by ndunand** [comment]
I guess I will now release this as 1.10.2.

**Comment by jpahullo** [comment]
Yes, I suppose too. :stuck_out_tongue_winking_eye:

**Comment by ndunand** [comment]
Done 😊
