### ISSUE TITLE
warning for accessing a non existing object

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#94]
```
( ! ) Notice: Trying to get property of non-object in /var/www/jpujol/moodle/admin/tool/mergeusers/lib/userreviewtable.php on line 100
Call Stack
#	Time	Memory	Function	Location
1	0.0005	295312	{main}( )	../index.php:0
2	2.9133	60707448	tool_mergeusers_renderer->index_page( )	../index.php:110
3	3.0164	60885816	tool_mergeusers_renderer->render_user_review_table( )	../renderer.php:127
4	3.0166	60917008	UserReviewTable->__construct( )	../renderer.php:152
5	3.0166	60918064	UserReviewTable->buildtable( )	../userreviewtable.php:85
```

How to reproduce:

1. Enable debug for developers in Moodle in a test environement.
2. Search for a user to merge in admin/tool/mergeusers/index.php.
3. Choose **only one user** either as a user to remove or to maintain (it does not matter).
4. Save selection.
5. When printing current selection you will see the above warning at the top.

It is produces by accessing directly to object attributes when one out of two objects may not exist yet:

Line 100 at userreviewtable.php:

```
if ($this->olduser->idnumber || $this->newuser->idnumber) {
```

Proposal to solve it: 

```
if (isset($this->olduser->idnumber) || isset($this->newuser->idnumber)) {
```

WIP

**Comment by jpahullo** [comment]
For the same issue, i found that there is a default empty column for the missing user.

Line 139 at userreviewtable.php:

```
       } else { // otherwise display empty fields
                $newuserrow[] = '';
                $newuserrow[] = '';
                $newuserrow[] = '';
            }
```

Proposal:

```
       } else { // otherwise display empty fields
                $newuserrow[] = '';
                $newuserrow[] = '';
                $newuserrow[] = '';
                $newuserrow[] = '';
            }
```

**Comment by jpahullo** [comment]
@ndunand could you review this issue please?

**Comment by ndunand** [comment]
Merged, thanks @jpahullo

**Comment by jpahullo** [comment]
Thanks for coming so quick @ndunand !!! This means tomorrow morning I will apply it into real :+1:  :smile:
