### ISSUE TITLE
compound indexes that do not apply to certain Moodle versions

### ISSUE THREAD

**Issue by jpahullo** [ndunand/moodle-tool_mergeusers#95]
From last update, we have found problems in our Moodle instance at real.

The error that prevented from making mergings was this compound index:

```
        'assign_grades' => array( //UNIQUE KEY mdl_assigrad_assuseatt_uix
            'userfield' => array('userid'),
            'otherfields' => array('assignment', 'attemptnumber'),
        ),
```

Column `attemptnumber` in my Moodle 2.4 does not exists and make it abort merging operations.

Proposal:

When initializing the tool (in the init() method), filter out those compound indexes with some missing column name according to current database scheme.

**Comment by jpahullo** [comment]
WIP.

**Comment by jpahullo** [comment]
@ndunand could you review this issue please?

**Comment by ndunand** [comment]
Thanks @jpahullo , that's really a good improvement 😊

**Comment by jpahullo** [comment]
Yes! I think so, and it will serve us in the future indeed, when automatic detection of compound indexes is going to be implemented: stored settings may differ from current database settings.

Thanks for going so quick resolving this PRs!!! I appreciate it very much @ndunand !!!
